### ISSUE TITLE
Unhandled exception during ARM Outputs Task TypeError: console.debug is not a function

### ISSUE THREAD

**Issue by jmezach** [keesschollaart81/vsts-arm-outputs#152] opened 2020-04-17 09:59 UTC
I made a change to my pipeline where I've set the `whenLastDeploymentIsFailed` option to `latestSuccesful` and now I'm getting the following error in my pipeline:

```
Starting: ARMOutputs
==============================================================================
Task         : ARM Outputs
Description  : This task reads the output values of an ARM deployment and sets them as Azure Pipelines variables.
Version      : 5.2.0
Author       : Kees Schollaart
Help         : [More Information](https://github.com/keesschollaart81/vsts-arm-outputs)
==============================================================================
Logging in using ApplicationTokenCredentials, authScheme is 'ServicePrincipal'
Unhandled exception during ARM Outputs Task TypeError: console.debug is not a function
    at ArmOutputs.eval (webpack://arm-outputs/./dist/arm-outputs.js?:26:29)
    at next (native)
    at fulfilled (webpack://arm-outputs/./dist/arm-outputs.js?:5:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
##[error]TypeError: console.debug is not a function
Finishing: ARMOutputs
```

Any idea what could be wrong here?

**Comment by Belicosus** [comment] 2020-07-17 08:51
I've run into this as well.
First, I thought this was a temporary issue on Microsfts end, since it seemed to come out of the blue. Going back, I realised it has to do with the "latestSuccesful" setting.

**Comment by keesschollaart81** [comment] 2020-07-19 08:21
I just pushed a fix for this: dab61dc I was not able to reproduce this as Node on my local machine and on the Ubuntu/Windows test agents seem to support console.debug. I changed console.debug to console.log as Google tells me console.debug can -indeed- break here and there.

**Comment by Belicosus** [comment] 2020-07-20 13:00
Perfect @keesschollaart81 ! I got desperate, and actually cloned your repo to publish a new extension with the fix. 
Couldn't reproduce locally either, but ended up with the same fix.

I'll pull "ARM Outputs Fork" from the Marketplace :-)
Thanks!

**Comment by keesschollaart81** [comment] 2020-07-20 13:02
Oeh, wow, sorry for that :-)

Anyway, you have to wait some more hours as I'm facing some challenges getting this release/fix out. I ran out of weekend-time yesterday so I have to solve this later this week. I'll report back here!

**Comment by Belicosus** [comment] 2020-07-21 11:36
I've left this one open, until you find the time:
https://marketplace.visualstudio.com/items?itemName=IteratorIT.arm-outputs-fork

**Comment by keesschollaart81** [comment] 2020-07-26 12:57
Rolling out as v6 now

**Closed by keesschollaart81** 2020-07-26 12:57 UTC
